mutation CreateArticle($parentId: Int, $title: String!, $projectId: Int!, $slug: String!) {
  insert_articles_one(
    object: { parent_id: $parentId, title: $title, project_id: $projectId, slug: $slug }
  ) {
    __typename
    id
    title
    parent_id
    project_id
    slug
    created_at
    updated_at
  }
}
