query GetArticles($project_id: Int!) {
  projects_by_pk(id: $project_id) {
    id
    articles {
      id
      parent_id
      slug
      title
      updated_at
      created_at #Remove these?
    }
  }
}
