subscription GetArticlesSubscription($projectId: Int!) {
  projects_by_pk(id: $projectId) {
    articles {
      id
      parent_id
      slug
      title
      updated_at
      created_at
    }
  }
}
