mutation UpdateArticle(
  $id: Int!
  $parent_id: Int
  $title: String
  $project_id: Int
  $slug: String
) {
  update_articles_by_pk(
    pk_columns: { id: $id }
    _set: { parent_id: $parent_id, title: $title, project_id: $parent_id, slug: $slug }
  ) {
    id
  }
}
