mutation updateUserActivity($articleId: Int!, $userId: Int!, $now: timestamptz!) {
  insert_articles_user_activity_one(
    object: { articleId: $articleId, userId: $userId, createdAt: $now }
    on_conflict: { constraint: articles_user_activity_pkey, update_columns: [createdAt] }
  ) {
    userId
    articleId
  }
}
