query GetArticleOne($slug: String!) {
  articles(where: { slug: { _eq: $slug } }) {
    id
    parentId
    projectId
    slug
    title
    updatedAt
    createdAt
    archived
    archivedAt
    position
  }
}
