fragment Article on articles {
  id
  parentId
  projectId
  title
  updatedAt
  createdAt
  archived
  archivedAt
  position
  path
  coverImage
  published
  publishedAt
  # archivedUser {
  #   id
  #   name
  # }
}
