#import "./ARTICLE_FRAGMENT.gql"
#import "../blocks/BLOCK_FRAGMENT.gql"

query GetArticleOne($path: String!) {
  articles(where: { path: { _eq: $path } }) {
    ...Article

    blocks {
      ...Block
    }
  }
}
