#import "./ARTICLE_FRAGMENT.gql"
#import "../blocks/BLOCK_FRAGMENT.gql"

query GetArticleOne($projectSlug: String!, $path: String!) {
  articles(where: { path: { _eq: $path }, project: { slug: { _eq: $projectSlug } } }) {
    ...Article

    blocks {
      ...Block
    }
  }
}
