mutation CreateProject($name: String!, $image: String, $organisation_id: Int!, $slug: String!) {
  insert_projects_one(
    object: { name: $name, image: $image, organisation_id: $organisation_id, slug: $slug }
  ) {
    id
  }
}
