#import "../articles/ARTICLE_FRAGMENT.gql"

fragment Project on projects {
  id
  name
  image
  slug
  articles: articles(where: { archived: { _eq: false } }) {
    ...Article
  }
  archivedArticles: articles(where: { archived: { _eq: true } }) {
    ...Article
  }
}
