#import "./BLOCK_FRAGMENT.gql"

mutation UpsertBlocks($objects: [blocks_insert_input!]!) {
  insert_blocks(
    objects: $objects
    on_conflict: {
      constraint: blocks_pkey
      update_columns: [parentId, payload, articleId, type, editingUserId, position]
    }
  ) {
    returning {
      ...Block
    }
  }
}
