subscription getUserActivity($articleId: Int!) {
  articles_user_activity(where: { articleId: { _eq: $articleId } }, order_by: { userId: asc }) {
    createdAt
    user {
      id
      name
      image
    }
  }
}
